#!/bin/bash

export WWWGROUP=""
export WWWUSER=1000

### EsLint is currently broken and will not be checked.
# docker-compose exec -T laravel.test npm run lint-eslint
docker-compose exec -T laravel.test npm run lint-prettier
